# Use custom format
format = "${custom.tab} $all"

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Don't print a new line at the start of the prompt
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
# success_symbol = "[â†’](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# vicmd_symbol = "[â†](bold red)"

# success_symbol = "[â®](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# vicmd_symbol = "[â®œ](bold red)"

# success_symbol = "[î· ](bold white)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# vicmd_symbol = "[î· ](bold red)"

#success_symbol = "[ï‡™ ](white)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
#vicmd_symbol = "[ï‡˜ ](red)"

success_symbol = "[ï„](bold white)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
vicmd_symbol = "[ï„€](bold red)"

#success_symbol = "[ï”ï”](white)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
#vicmd_symbol = "[ï“ï“](red)"
# vicmd_symbol = "[îŸ… ](bold red)"

#success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
#vicmd_symbol = "[î˜«](bold red)"

# success_symbol = "[â—‹ ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# vicmd_symbol = "[â—‰ ](bold red)"

# success_symbol = "[ï•“](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# vicmd_symbol = "[É‘](bold red)
[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"
show_notifications = true
min_time_to_notify = 45_000
style = "bold yellow"

[battery]
disabled = false
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[time]
disabled = true
time_format = "%T"
format = "at ğŸ•™[$time]($style) "

[[battery.display]]
threshold = 15
style = "bold red"

[java]
symbol = "ğŸµ "
style = "bold blue"
format = "[$symbol$version ]($style) "

[status]
style = "bg:red"
symbol = "âœ˜ "
format = '[\[$symbol$status\]]($style) '
disabled = false

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = false

[aws]
symbol = "îŒ½ "
style = "bold blue"
format = "[$symbol$version ]($style) "

# [battery]
# full_symbol = "ï•¸"
# charging_symbol = "ï–ƒ"
# discharging_symbol = "ï–‚"

[conda]
symbol = "ï„Œ "
style = "bold blue"
format = "[$symbol$version ]($style) "

[dart]
symbol = "î˜ "
style = "bold blue"
format = "[$symbol$version ]($style) "

[docker]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "
style = "bold blue"
format = "[$symbol$version ]($style) "

[elm]
symbol = "î˜¬ "
style = "bold blue"
format = "[$symbol$version ]($style) "

[git_branch]
symbol = "ï˜ "

[golang]
symbol = "î˜§ "
style = "bold blue"
format = "[$symbol$version ]($style) "

[haskell]
symbol = "î˜Ÿ "
style = "bold blue"
format = "[$symbol$version ]($style) "

[hg_branch]
symbol = "ï˜ "

[julia]
symbol = "î˜¤ "
style = "bold blue"
format = "[$symbol$version ]($style) "

[memory_usage]
disabled = false
threshold = 75
symbol = "ï¡š "
style = "bold dimmed blue"
format = " $symbol [${ram}]($style) "

[nim]
symbol = "ïš¤ "
style = "bold blue"
format = "[$symbol$version ]($style) "

[nix_shell]
symbol = "ï‹œ "
style = "bold blue"
format = "[$symbol$version ]($style) "

[nodejs]
symbol = "î‰ "
style = "bold blue"
format = "[$symbol$version ]($style) "

[package]
symbol = "ï£– "
style = "bold blue"
format = "[$symbol$version ]($style) "

[perl]
symbol = "î© "
style = "bold blue"
format = "[$symbol$version ]($style) "

[php]
symbol = "ğŸ˜"
style = "bold blue"
format = "[$symbol$version ]($style) "

[python]
symbol = "î˜† "
style = "bold blue"
format = "[$symbol$version ]($style) "

[ruby]
symbol = "îˆ¾ "
style = "bold blue"
format = "[$symbol$version ]($style) "

[rust]
#symbol = "î¨ "
symbol = "ğŸ¦€ "
style = "bold red"
format = "[$symbol$version ]($style) "

[swift]
symbol = "ï¯£ "
style = "bold blue"
format = "[$symbol$version ]($style) "

[directory]
truncation_length = 8
truncation_symbol = "â€¦/"

[custom]

[custom.tab]
description = "The current tab in the tab terminal multiplexer"
command = "tab --starship"
when = "tab --starship"
shell = ["sh"]
format = "[$output]($style) "
style = "bold blue"


