# Use custom format
format = "$all"

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Don't print a new line at the start of the prompt
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
# success_symbol = "[â†’](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# vicmd_symbol = "[â†](bold red)"

# success_symbol = "[â®](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# vicmd_symbol = "[â®œ](bold red)"

# success_symbol = "[î· ](bold white)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# vicmd_symbol = "[î· ](bold red)"

# success_symbol = "[ï‡™ ](white)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# vicmd_symbol = "[ï‡˜ ](red)"

success_symbol = "[ï„](bold white)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
vicmd_symbol = "[ï„€](bold red)"

# success_symbol = "[ï”](white)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# vicmd_symbol = "[ï“](red)"
# vicmd_symbol = "[îŸ… ](bold red)"

# success_symbol = "[âœ ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# vicmd_symbol = "[î˜« ](bold red)"

# success_symbol = "[â—‹ ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# vicmd_symbol = "[â—‰ ](bold red)"

# success_symbol = "[ï•“](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# vicmd_symbol = "[É‘](bold red)
[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"
show_notifications = true
min_time_to_notify = 45_000
style = "bold yellow"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[time]
disabled = true
time_format = "%T"
format = "at ğŸ•™[$time]($style) "

[[battery.display]]
threshold = 15
style = "bold red"

[java]
symbol = "ğŸµ "
style = "bold blue"
format = "[$symbol$version ]($style) "

[status]
style = "bg:red"
symbol = "âœ˜ "
format = '[\[$symbol$status\]]($style) '
disabled = false

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = false

[aws]
symbol = "îŒ½ "

# [battery]
# full_symbol = "ï•¸"
# charging_symbol = "ï–ƒ"
# discharging_symbol = "ï–‚"

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
symbol = "ï˜ "

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î˜Ÿ "

[hg_branch]
symbol = "ï˜ "

[julia]
symbol = "î˜¤ "

[memory_usage]
disabled = false
threshold = 75
symbol = "ï¡š "
style = "bold dimmed blue"
format = " $symbol [${ram}]($style) "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "î‰ "

[package]
symbol = "ï£– "

[perl]
symbol = "î© "

[php]
symbol = "ğŸ˜"

[python]
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

# [rust]
# symbol = "î¨ "

[swift]
symbol = "ï¯£ "

[directory]
truncation_length = 8
truncation_symbol = "â€¦/"


